Passwordstrength
angelayke/gestion-budget-etudiant pull request #3
Opened 2023-04-23 15:51 UTC by joslsinfo

2023-04-23 16:27 UTC, angelayke reviewed
Il semblerait qu'il y a du nettoyage à faire

2023-04-23 16:29 UTC, mattheri requested changes

2023-04-23 16:29 UTC, mattheri commented on src/app/interfaces/expense.interface.ts
> +type Expense =
Il faut que tu exportes le type

2023-04-23 16:29 UTC, mattheri commented on src/app/services/password.service.ts
> +    console.log("Test......................", result);
Enlève les console.log

2023-04-23 16:29 UTC, mattheri commented on src/app/services/password.service.ts
> +// import * as passwordStrength from 'check-password-strength';
Enlève les comments qui ne servent plus à rien

2023-04-23 16:29 UTC, mattheri commented on src/app/services/expense.service.ts
Ce fichier n'est pas supposé être inclus. Ça me dit donc que tu n'es pas reparti de `main` pour faire ta nouvelle branche ce qui n'est pas correct.

Fait cette commande `git rm src/app/services/expense.service.ts --cached` puis commit/push

2023-04-23 16:29 UTC, mattheri commented on src/app/services/expense.service.spec.ts
> +import { TestBed } from '@angular/core/testing';
Ce fichier n'est pas supposé être inclus. Ça me dit donc que tu n'es pas reparti de main pour faire ta nouvelle branche ce qui n'est pas correct.

Fait cette commande git rm src/app/services/expense.service.spec.ts --cached puis commit/push

2023-04-23 17:41 UTC, joslsinfo commented on src/app/services/expense.service.ts
Changement a été fait.

2023-04-23 17:41 UTC, joslsinfo commented on src/app/services/expense.service.spec.ts
> +import { TestBed } from '@angular/core/testing';
Changement a été fait.

2023-04-25 00:04 UTC, mattheri approved these changes

2023-04-25 00:04 UTC, merged