Calculatrice style update
angelayke/gestion-budget-etudiant pull request #42
Opened 2023-05-15 02:51 UTC by TamanacoMartinez

mise a jour style calculatrice

2023-05-15 22:48 UTC, mattheri requested changes

2023-05-15 22:48 UTC, mattheri commented on src/app/components/calculatrice/calculatrice.component.scss
> +    // background-color: #000;
Enlève tout ce qui en commentaire, ce n'est pas nécessaire

2023-05-20 02:54 UTC, TamanacoMartinez commented on src/app/components/calculatrice/calculatrice.component.scss
> +    // background-color: #000;
c'est fait...J'ai enlèvé les commentaires

2023-05-23 22:34 UTC, mattheri approved these changes

2023-05-23 22:34 UTC, mattheri approved these changes

2023-05-23 23:49 UTC, angelayke approved these changes

2023-05-23 23:51 UTC, merged